name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        workdir: .
        buildozer_version: stable
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MPerformance-Password-APK
        path: ${{ steps.buildozer.outputs.filename }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: v1.0.0
        name: M-Performance Pass v1.0.0
        files: ${{ steps.buildozer.outputs.filename }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
